Show dialog after first run
dart-lang/dart-pad pull request #2397
Opened 2022-10-28 20:30 UTC by johnpryan

experimental - [staged here](https://20221028t132153-dot-dart-pad.appspot.com/?)

2022-10-31 19:09 UTC, maguinis commented
@johnpryan can we update the text to: 

"Success! While you are building with DartPad, let’s get Flutter installed in the background so that you can unlock all features (like Hot Reload). **Click here to install** in a new tab."

2022-10-31 19:14 UTC, maguinis commented
Other thoughts: 

- Open the link to install on a new tab vs. the same dartpad tab
- Update the Install SDK link to always be Flutter install

2022-10-31 19:21 UTC, jayoung-lee commented
It will be useful to add a campaign ID to the URL, so that we can track this from the website analytics. 
Documentation: https://support.google.com/analytics/answer/1033863

2022-10-31 19:26 UTC, jayoung-lee commented
The button on the message prompt says "OK", which is ambiguous. Can we change it to something like "Dismiss"?

And I think the message could be shorter, like:
```
Success!

Click here to install Flutter SDK and unlock all the features like Hot Reload. 
```

2022-11-02 21:48 UTC, johnpryan commented
>  Can we change it to something like "Dismiss"

Unfortunately, no. Here are the options we have available:

```dart
```

2022-11-02 23:17 UTC, jayoung-lee commented
That's a bummer! What if we remove the button altogether and just have a little [x] on the top right corner?

2022-11-09 17:35 UTC, jayoung-lee commented on lib/playground.dart
> +            r'<a class="link-bright" href="https://docs.flutter.dev/get-started/install?utm_campaign=dartpad_install">'
A custom campaign needs all three parameters: `utm_source`, `utm_medium`, and `utm_campaign`. Could you update the URL to `?utm_source=dartpad.dev&utm_medium=referral&utm_campaign=dartpad_install`

2022-11-09 17:36 UTC, jayoung-lee requested changes
Could you update the URL?

2022-11-09 18:24 UTC, johnpryan commented
@jayoung-lee thanks, that's updated now.

2022-11-11 18:32 UTC, closed without merging